// 物品词表 —— 逐字对齐 app/lib/core/goods_lexicon.dart（docs/29 §2.3）
// 表体由 Dart 真源生成；一致性由 tools/web-parity.mjs 第⑥块钉住：有任何一词之差、
// 任何一条顺序不同、任何一类缺失，闸门即红。手抄 300+ 条必然出错，所以这条不许省。
// 与 lexicon.js 的关系是**并列而非从属**：category 答「哪门子开销」，goods_cat 答「买回来的是
// 个什么东西」，物品维度永不覆盖 category，也不从 category 反推。
export const GOODS_OTHER = { name: '其他物品', emoji: '📦' };

export const GOODS_CATEGORIES = [
  { name: '食品', emoji: '🍚' },
  { name: '饮品', emoji: '🥤' },
  { name: '服饰', emoji: '👕' },
  { name: '鞋包', emoji: '👟' },
  { name: '美妆个护', emoji: '🧴' },
  { name: '数码', emoji: '💻' },
  { name: '家电', emoji: '🔌' },
  { name: '日用', emoji: '🧻' },
  { name: '家居', emoji: '🛏' },
  { name: '母婴', emoji: '🍼' },
  { name: '宠物', emoji: '🐾' },
  { name: '健康药械', emoji: '💊' },
  { name: '文娱', emoji: '🎬' },
  { name: '交通件', emoji: '🚗' },
];

// word = 去原话里找的那串字；item = 落库显示的物品名（空串时同 word）
export const GOODS_WORDS = [
  { word: '米饭', cat: '食品', item: '' },
  { word: '面条', cat: '食品', item: '' },
  { word: '饺子', cat: '食品', item: '' },
  { word: '包子', cat: '食品', item: '' },
  { word: '馒头', cat: '食品', item: '' },
  { word: '面包', cat: '食品', item: '' },
  { word: '蛋糕', cat: '食品', item: '' },
  { word: '月饼', cat: '食品', item: '' },
  { word: '粽子', cat: '食品', item: '' },
  { word: '牛奶', cat: '食品', item: '' },
  { word: '酸奶', cat: '食品', item: '' },
  { word: '奶酪', cat: '食品', item: '' },
  { word: '黄油', cat: '食品', item: '' },
  { word: '鸡蛋', cat: '食品', item: '' },
  { word: '牛排', cat: '食品', item: '' },
  { word: '牛肉', cat: '食品', item: '' },
  { word: '猪肉', cat: '食品', item: '' },
  { word: '鸡肉', cat: '食品', item: '' },
  { word: '鸡腿', cat: '食品', item: '' },
  { word: '鸡翅', cat: '食品', item: '' },
  { word: '三文鱼', cat: '食品', item: '' },
  { word: '虾滑', cat: '食品', item: '' },
  { word: '火锅', cat: '食品', item: '' },
  { word: '火锅食材', cat: '食品', item: '' },
  { word: '烧烤', cat: '食品', item: '' },
  { word: '零食', cat: '食品', item: '' },
  { word: '薯片', cat: '食品', item: '' },
  { word: '巧克力', cat: '食品', item: '' },
  { word: '糖果', cat: '食品', item: '' },
  { word: '饼干', cat: '食品', item: '' },
  { word: '坚果', cat: '食品', item: '' },
  { word: '瓜子', cat: '食品', item: '' },
  { word: '香蕉', cat: '食品', item: '' },
  { word: '橙子', cat: '食品', item: '' },
  { word: '葡萄', cat: '食品', item: '' },
  { word: '草莓', cat: '食品', item: '' },
  { word: '蓝莓', cat: '食品', item: '' },
  { word: '榴莲', cat: '食品', item: '' },
  { word: '西瓜', cat: '食品', item: '' },
  { word: '桃子', cat: '食品', item: '' },
  { word: '蔬菜', cat: '食品', item: '' },
  { word: '西红柿', cat: '食品', item: '' },
  { word: '黄瓜', cat: '食品', item: '' },
  { word: '土豆', cat: '食品', item: '' },
  { word: '白菜', cat: '食品', item: '' },
  { word: '大米', cat: '食品', item: '' },
  { word: '面粉', cat: '食品', item: '' },
  { word: '食用油', cat: '食品', item: '' },
  { word: '调味料', cat: '食品', item: '' },
  { word: '调料', cat: '食品', item: '' },
  { word: '酱油', cat: '食品', item: '' },
  { word: '外卖', cat: '食品', item: '' },
  { word: '奶茶', cat: '饮品', item: '' },
  { word: '咖啡', cat: '饮品', item: '' },
  { word: '拿铁', cat: '饮品', item: '' },
  { word: '美式咖啡', cat: '饮品', item: '美式' },
  { word: '生椰拿铁', cat: '饮品', item: '' },
  { word: '卡布奇诺', cat: '饮品', item: '' },
  { word: '果茶', cat: '饮品', item: '' },
  { word: '柠檬茶', cat: '饮品', item: '' },
  { word: '矿泉水', cat: '饮品', item: '' },
  { word: '纯净水', cat: '饮品', item: '' },
  { word: '可乐', cat: '饮品', item: '' },
  { word: '气泡水', cat: '饮品', item: '' },
  { word: '果汁', cat: '饮品', item: '' },
  { word: '豆浆', cat: '饮品', item: '' },
  { word: '啤酒', cat: '饮品', item: '' },
  { word: '红酒', cat: '饮品', item: '' },
  { word: '白酒', cat: '饮品', item: '' },
  { word: '茶叶', cat: '饮品', item: '' },
  { word: '饮料', cat: '饮品', item: '' },
  { word: '衣服', cat: '服饰', item: '' },
  { word: 'T恤', cat: '服饰', item: '' },
  { word: '衬衫', cat: '服饰', item: '' },
  { word: '裤子', cat: '服饰', item: '' },
  { word: '牛仔裤', cat: '服饰', item: '' },
  { word: '短裤', cat: '服饰', item: '' },
  { word: '外套', cat: '服饰', item: '' },
  { word: '夹克', cat: '服饰', item: '' },
  { word: '羽绒服', cat: '服饰', item: '' },
  { word: '棉服', cat: '服饰', item: '' },
  { word: '毛衣', cat: '服饰', item: '' },
  { word: '卫衣', cat: '服饰', item: '' },
  { word: '风衣', cat: '服饰', item: '' },
  { word: '大衣', cat: '服饰', item: '' },
  { word: '西装', cat: '服饰', item: '' },
  { word: '裙子', cat: '服饰', item: '' },
  { word: '连衣裙', cat: '服饰', item: '' },
  { word: '内衣', cat: '服饰', item: '' },
  { word: '内裤', cat: '服饰', item: '' },
  { word: '袜子', cat: '服饰', item: '' },
  { word: '睡衣', cat: '服饰', item: '' },
  { word: '帽子', cat: '服饰', item: '' },
  { word: '围巾', cat: '服饰', item: '' },
  { word: '手套', cat: '服饰', item: '' },
  { word: '腰带', cat: '服饰', item: '' },
  { word: '鞋子', cat: '鞋包', item: '' },
  { word: '运动鞋', cat: '鞋包', item: '' },
  { word: '跑鞋', cat: '鞋包', item: '' },
  { word: '篮球鞋', cat: '鞋包', item: '' },
  { word: '皮鞋', cat: '鞋包', item: '' },
  { word: '凉鞋', cat: '鞋包', item: '' },
  { word: '拖鞋', cat: '鞋包', item: '' },
  { word: '靴子', cat: '鞋包', item: '' },
  { word: '帆布鞋', cat: '鞋包', item: '' },
  { word: '球鞋', cat: '鞋包', item: '' },
  { word: '包包', cat: '鞋包', item: '' },
  { word: '背包', cat: '鞋包', item: '' },
  { word: '书包', cat: '鞋包', item: '' },
  { word: '钱包', cat: '鞋包', item: '' },
  { word: '行李箱', cat: '鞋包', item: '' },
  { word: '旅行箱', cat: '鞋包', item: '' },
  { word: '洗面奶', cat: '美妆个护', item: '' },
  { word: '面霜', cat: '美妆个护', item: '' },
  { word: '面膜', cat: '美妆个护', item: '' },
  { word: '精华', cat: '美妆个护', item: '' },
  { word: '口红', cat: '美妆个护', item: '' },
  { word: '粉底', cat: '美妆个护', item: '' },
  { word: '睫毛膏', cat: '美妆个护', item: '' },
  { word: '防晒霜', cat: '美妆个护', item: '' },
  { word: '香水', cat: '美妆个护', item: '' },
  { word: '洗发水', cat: '美妆个护', item: '' },
  { word: '护发素', cat: '美妆个护', item: '' },
  { word: '发膜', cat: '美妆个护', item: '' },
  { word: '沐浴露', cat: '美妆个护', item: '' },
  { word: '身体乳', cat: '美妆个护', item: '' },
  { word: '牙膏', cat: '美妆个护', item: '' },
  { word: '牙刷', cat: '美妆个护', item: '' },
  { word: '电动牙刷', cat: '美妆个护', item: '' },
  { word: '漱口水', cat: '美妆个护', item: '' },
  { word: '剃须刀', cat: '美妆个护', item: '' },
  { word: '吹风机', cat: '美妆个护', item: '' },
  { word: '护手霜', cat: '美妆个护', item: '' },
  { word: '护肤品', cat: '美妆个护', item: '' },
  { word: '化妆品', cat: '美妆个护', item: '' },
  { word: '手机', cat: '数码', item: '' },
  { word: '苹果手机', cat: '数码', item: '手机' },
  { word: '手机壳', cat: '数码', item: '' },
  { word: '耳机', cat: '数码', item: '' },
  { word: '无线耳机', cat: '数码', item: '耳机' },
  { word: '充电器', cat: '数码', item: '' },
  { word: '充电线', cat: '数码', item: '' },
  { word: '充电宝', cat: '数码', item: '' },
  { word: '电脑', cat: '数码', item: '' },
  { word: '笔记本', cat: '数码', item: '' },
  { word: '笔记本电脑', cat: '数码', item: '笔记本' },
  { word: '平板', cat: '数码', item: '' },
  { word: '显示器', cat: '数码', item: '' },
  { word: '键盘', cat: '数码', item: '' },
  { word: '鼠标', cat: '数码', item: '' },
  { word: '鼠标垫', cat: '数码', item: '' },
  { word: '音箱', cat: '数码', item: '' },
  { word: '路由器', cat: '数码', item: '' },
  { word: '显卡', cat: '数码', item: '' },
  { word: '硬盘', cat: '数码', item: '' },
  { word: '内存条', cat: '数码', item: '' },
  { word: 'U盘', cat: '数码', item: '' },
  { word: '相机', cat: '数码', item: '' },
  { word: '镜头', cat: '数码', item: '' },
  { word: '三脚架', cat: '数码', item: '' },
  { word: '无人机', cat: '数码', item: '' },
  { word: '手表', cat: '数码', item: '' },
  { word: '智能手表', cat: '数码', item: '手表' },
  { word: '手环', cat: '数码', item: '' },
  { word: '游戏机', cat: '数码', item: '' },
  { word: 'Switch', cat: '数码', item: '游戏机' },
  { word: '数据线', cat: '数码', item: '' },
  { word: '支架', cat: '数码', item: '' },
  { word: '空调', cat: '家电', item: '' },
  { word: '冰箱', cat: '家电', item: '' },
  { word: '洗衣机', cat: '家电', item: '' },
  { word: '电视', cat: '家电', item: '' },
  { word: '微波炉', cat: '家电', item: '' },
  { word: '电饭煲', cat: '家电', item: '' },
  { word: '电饭锅', cat: '家电', item: '电饭煲' },
  { word: '电磁炉', cat: '家电', item: '' },
  { word: '烤箱', cat: '家电', item: '' },
  { word: '空气炸锅', cat: '家电', item: '' },
  { word: '吸尘器', cat: '家电', item: '' },
  { word: '扫地机器人', cat: '家电', item: '' },
  { word: '净水器', cat: '家电', item: '' },
  { word: '热水器', cat: '家电', item: '' },
  { word: '加湿器', cat: '家电', item: '' },
  { word: '电风扇', cat: '家电', item: '风扇' },
  { word: '取暖器', cat: '家电', item: '' },
  { word: '豆浆机', cat: '家电', item: '' },
  { word: '榨汁机', cat: '家电', item: '' },
  { word: '纸巾', cat: '日用', item: '' },
  { word: '抽纸', cat: '日用', item: '' },
  { word: '湿巾', cat: '日用', item: '' },
  { word: '厕纸', cat: '日用', item: '' },
  { word: '洗衣液', cat: '日用', item: '' },
  { word: '洗衣粉', cat: '日用', item: '' },
  { word: '柔顺剂', cat: '日用', item: '' },
  { word: '洗洁精', cat: '日用', item: '' },
  { word: '消毒液', cat: '日用', item: '' },
  { word: '垃圾袋', cat: '日用', item: '' },
  { word: '拖把', cat: '日用', item: '' },
  { word: '扫帚', cat: '日用', item: '' },
  { word: '抹布', cat: '日用', item: '' },
  { word: '收纳箱', cat: '日用', item: '' },
  { word: '雨伞', cat: '日用', item: '' },
  { word: '保温杯', cat: '日用', item: '' },
  { word: '水杯', cat: '日用', item: '' },
  { word: '餐具', cat: '日用', item: '' },
  { word: '筷子', cat: '日用', item: '' },
  { word: '砧板', cat: '日用', item: '' },
  { word: '保鲜膜', cat: '日用', item: '' },
  { word: '电池', cat: '日用', item: '' },
  { word: '灯泡', cat: '日用', item: '' },
  { word: '打火机', cat: '日用', item: '' },
  { word: '床单', cat: '家居', item: '' },
  { word: '被套', cat: '家居', item: '' },
  { word: '被罩', cat: '家居', item: '被套' },
  { word: '枕头', cat: '家居', item: '' },
  { word: '被子', cat: '家居', item: '' },
  { word: '床垫', cat: '家居', item: '' },
  { word: '四件套', cat: '家居', item: '' },
  { word: '窗帘', cat: '家居', item: '' },
  { word: '地毯', cat: '家居', item: '' },
  { word: '沙发', cat: '家居', item: '' },
  { word: '桌子', cat: '家居', item: '' },
  { word: '书桌', cat: '家居', item: '' },
  { word: '椅子', cat: '家居', item: '' },
  { word: '柜子', cat: '家居', item: '' },
  { word: '置物架', cat: '家居', item: '' },
  { word: '台灯', cat: '家居', item: '' },
  { word: '吊灯', cat: '家居', item: '' },
  { word: '挂钟', cat: '家居', item: '' },
  { word: '绿植', cat: '家居', item: '' },
  { word: '花盆', cat: '家居', item: '' },
  { word: '纸尿裤', cat: '母婴', item: '' },
  { word: '尿不湿', cat: '母婴', item: '纸尿裤' },
  { word: '奶粉', cat: '母婴', item: '' },
  { word: '奶瓶', cat: '母婴', item: '' },
  { word: '婴儿车', cat: '母婴', item: '' },
  { word: '安全座椅', cat: '母婴', item: '' },
  { word: '辅食', cat: '母婴', item: '' },
  { word: '婴儿米粉', cat: '母婴', item: '辅食' },
  { word: '童装', cat: '母婴', item: '' },
  { word: '玩具', cat: '母婴', item: '' },
  { word: '积木', cat: '母婴', item: '' },
  { word: '猫粮', cat: '宠物', item: '' },
  { word: '狗粮', cat: '宠物', item: '' },
  { word: '猫砂', cat: '宠物', item: '' },
  { word: '猫罐头', cat: '宠物', item: '' },
  { word: '冻干', cat: '宠物', item: '' },
  { word: '宠物零食', cat: '宠物', item: '' },
  { word: '驱虫药', cat: '宠物', item: '' },
  { word: '牵引绳', cat: '宠物', item: '' },
  { word: '猫窝', cat: '宠物', item: '' },
  { word: '狗窝', cat: '宠物', item: '' },
  { word: '猫爬架', cat: '宠物', item: '' },
  { word: '鱼缸', cat: '宠物', item: '' },
  { word: '感冒药', cat: '健康药械', item: '' },
  { word: '退烧药', cat: '健康药械', item: '' },
  { word: '止咳药', cat: '健康药械', item: '' },
  { word: '胃药', cat: '健康药械', item: '' },
  { word: '止痛药', cat: '健康药械', item: '' },
  { word: '维生素', cat: '健康药械', item: '' },
  { word: '钙片', cat: '健康药械', item: '' },
  { word: '蛋白粉', cat: '健康药械', item: '' },
  { word: '保健品', cat: '健康药械', item: '' },
  { word: '口罩', cat: '健康药械', item: '' },
  { word: '体温计', cat: '健康药械', item: '' },
  { word: '血压计', cat: '健康药械', item: '' },
  { word: '血氧仪', cat: '健康药械', item: '' },
  { word: '创可贴', cat: '健康药械', item: '' },
  { word: '膏药', cat: '健康药械', item: '' },
  { word: '血糖仪', cat: '健康药械', item: '' },
  { word: '电影票', cat: '文娱', item: '' },
  { word: '门票', cat: '文娱', item: '' },
  { word: '游戏', cat: '文娱', item: '' },
  { word: '游戏点卡', cat: '文娱', item: '游戏' },
  { word: '会员卡', cat: '文娱', item: '会员' },
  { word: '会员', cat: '文娱', item: '会员' },
  { word: '手办', cat: '文娱', item: '' },
  { word: '图书', cat: '文娱', item: '' },
  { word: '本书', cat: '文娱', item: '图书' },
  { word: '童书', cat: '文娱', item: '童书' },
  { word: '绘本', cat: '文娱', item: '' },
  { word: '文具', cat: '文娱', item: '' },
  { word: '笔袋', cat: '文娱', item: '' },
  { word: '笔记本子', cat: '文娱', item: '本子' },
  { word: '颜料', cat: '文娱', item: '' },
  { word: '画笔', cat: '文娱', item: '' },
  { word: '吉他', cat: '文娱', item: '' },
  { word: '尤克里里', cat: '文娱', item: '' },
  { word: '钢琴课', cat: '文娱', item: '琴课' },
  { word: '健身卡', cat: '文娱', item: '健身' },
  { word: '泳卡', cat: '文娱', item: '游泳' },
  { word: '球拍', cat: '文娱', item: '' },
  { word: '羽毛球拍', cat: '文娱', item: '球拍' },
  { word: '轮胎', cat: '交通件', item: '' },
  { word: '机油', cat: '交通件', item: '' },
  { word: '车膜', cat: '交通件', item: '' },
  { word: '脚垫', cat: '交通件', item: '' },
  { word: '行车记录仪', cat: '交通件', item: '' },
  { word: '车载支架', cat: '交通件', item: '车支架' },
  { word: '车载充电器', cat: '交通件', item: '车充' },
  { word: '头盔', cat: '交通件', item: '' },
  { word: '自行车', cat: '交通件', item: '' },
  { word: '电动车', cat: '交通件', item: '' },
  { word: '平衡车', cat: '交通件', item: '' },
  { word: '滑板', cat: '交通件', item: '' },
  { word: '滑轮鞋', cat: '交通件', item: '轮滑鞋' },
  { word: '洗车', cat: '交通件', item: '' },
  { word: '油卡', cat: '交通件', item: '' },
  { word: '公交卡', cat: '交通件', item: '' },
  { word: '地铁卡', cat: '交通件', item: '' },
  { word: '船票', cat: '交通件', item: '' },
  { word: '火车票', cat: '交通件', item: '' },
  { word: '机票', cat: '交通件', item: '' },
];

export const goodsDisplay = (w) => (w.item === '' ? w.word : w.item);

// 大类名（含兜底），按 GOODS_CATEGORIES 的书写次序——平手时的稳定次序就靠它。
export function goodsCategoryNames() {
  return [...GOODS_CATEGORIES.map((c) => c.name), GOODS_OTHER.name];
}

// 图标找不到时回兜底，绝不崩（导入来的陌生类名也要能显示）。
export function goodsIcon(name) {
  const c = GOODS_CATEGORIES.find((x) => x.name === name);
  return c ? c.emoji : GOODS_OTHER.emoji;
}

// 聚合键：剥括号补充说明、去空白、转小写。不做同音纠错——纠错属于纠错层，
// 混进键里等于让「同一件东西」的判定随词典更新而漂移。
export function goodsNorm(s) {
  return s
    .replace(/[（(][^（()）]*[)）]/g, '')
    .replace(/\s+/g, '')
    .trim()
    .toLowerCase();
}

// 显示名反查大类：认不出来落兜底类。
export function goodsCatOfDisplay(item) {
  for (const w of GOODS_WORDS) if (goodsDisplay(w) === item) return w.cat;
  return GOODS_OTHER.name;
}

const AMOUNT_CHARS = '0123456789零一二两三四五六七八九十百千万块元角毛钱折倍';
// 与 Dart 的 runes.length 同口径：数码点，不是数 UTF-16 单元
const runes = (s) => [...s].length;

// 词条合法性：与 Dart 的 goodsWordProblem 逐条同判据（闸门两边各跑一次）。
export function goodsWordProblem(w) {
  if (w.word === '') return '空词';
  if (runes(w.word) < 2) return '单字词一律不许进物品词表：' + w.word;
  if (runes(w.word) > 8) return '词条最长 8 个字：' + w.word;
  if (/\s/.test(w.word)) return '词条里不许有空格：' + w.word;
  if ([...w.word].every((ch) => AMOUNT_CHARS.includes(ch)))
    return '整条词都是数字/金额字，会从金额里抽出物品：' + w.word;
  if (!goodsCategoryNames().includes(w.cat)) return '大类不存在：' + w.cat;
  return null;
}
